project_id = "zesvmrjdmwrqsxwckcwe"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.login-with-username]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.send-notification]
verify_jwt = false